name: 'Check for a new release'
description: 'Check if a new release is required by checking package.json'
author: 'Adhityan'
inputs:
  need_past_versions:
    description: '`true` to get a list of all past versions'
    required: false
    default: 'false'
  generate_conventional_changelog:
    description: '`true` to generate a changelog string for conventional commits'
    required: false
    default: 'true'
outputs:
  has_new_version:
    description: '`true` if this introduces a new version'
  has_existing_version:
    description: '`true` if there already is a matching published version'
  all_past_versions:
    description: 'A list of all past published versions'
  current_release_version:
    description: 'The release version from current package.json'
  maximum_past_release_version:
    description: 'The last maximum release version from releases list'
  conventional_changelog:
    description: 'The conventional changelog for the commits'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'tag'
  color: 'gray-dark'
